import random

def generate_traffic():
    return {
        "dur": round(random.uniform(0, 10), 3),
        "proto": random.choice([0, 1, 2]),        # encoded tcp/udp/icmp
        "service": random.choice([0, 1, 2, 3]),
        "state": random.choice([0, 1, 2]),
        "spkts": random.randint(1, 500),
        "dpkts": random.randint(1, 500),
        "sbytes": random.randint(100, 50000),
        "dbytes": random.randint(100, 50000),
        "rate": random.uniform(1, 1000),
        "sload": random.uniform(1, 10000),
        "dload": random.uniform(1, 10000),
        "sloss": random.randint(0, 5),
        "dloss": random.randint(0, 5),
        "sinpkt": random.uniform(0, 100),
        "dinpkt": random.uniform(0, 100),
        "sjit": random.uniform(0, 50),
        "djit": random.uniform(0, 50),
        "swin": random.randint(0, 65535),
        "stcpb": random.randint(0, 100000),
        "dtcpb": random.randint(0, 100000),
        "dwin": random.randint(0, 65535),
        "tcprtt": random.uniform(0, 10),
        "synack": random.uniform(0, 5),
        "ackdat": random.uniform(0, 5),
        "smean": random.uniform(0, 500),
        "dmean": random.uniform(0, 500),
        "trans_depth": random.randint(0, 10),
        "response_body_len": random.randint(0, 5000),
        "ct_src_dport_ltm": random.randint(0, 50),
        "ct_dst_sport_ltm": random.randint(0, 50),
        "is_ftp_login": random.randint(0, 1),
        "ct_ftp_cmd": random.randint(0, 10),
        "ct_flw_http_mthd": random.randint(0, 10),
        "is_sm_ips_ports": random.randint(0, 1),
    }
